name: Docker build & test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: create DuckDB database
        run: Rscript extras/createDuckdbDatabase.R

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          load: true
          tags: omop-constructor:ci
          build-args: |
            CI=true

      # check docker was created successfully
      - name: Check R + package load
        run: |
          docker run --rm \
            -e DB_SERVER=gibleed.duckdb \
            -e DBMS=duckdb \
            -e CDM_SCHEMA=cdm \
            -e RESULTS_SCHEMA=main \
            -e persistenceDays=180 \
            -e collapseDays=180 \
            omop-constructor:ci
